### ISSUE TITLE
Local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by Elusv** [obaskly/AiTextDetectionBypass#10]
console error: Error during article submission: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

Gui error: Local variable 'driver' referenced before assignment

credentials.json in folder as instructed.  Chrome is installed (using it now).  what up?

**Comment by obaskly** [comment]
can you try again now. I have updated the script
