### ISSUE TITLE
the program is stuck at the login page

### ISSUE THREAD

**Issue by zmatical** [obaskly/AiTextDetectionBypass#3]
is there a possible fix for the program being stuck at the login page?
the program is stuck at logging page and doesn't perform any automations, though it seems that some accounts are recorded in the accounts.txt 
additionally, the chromium just gets a blank data; page while it didn't perform anything
then it returns back to logging page and it's an endless cycle after long wait of nothingness

Error during registration: Message: 
Stacktrace:
        GetHandleVerifier [0x00007FF6081F5E42+3538674]
        (No symbol) [0x00007FF607E14C02]
        (No symbol) [0x00007FF607CC5AEB]
        (No symbol) [0x00007FF607D0BF4E]
        (No symbol) [0x00007FF607D0C0CC]
        (No symbol) [0x00007FF607D4E477]
        (No symbol) [0x00007FF607D2F0EF]
        (No symbol) [0x00007FF607D4BDE3]
        (No symbol) [0x00007FF607D2EE53]
        (No symbol) [0x00007FF607CFF514]
        (No symbol) [0x00007FF607D00631]
        GetHandleVerifier [0x00007FF608226CAD+3738973]
        GetHandleVerifier [0x00007FF60827C506+4089270]
        GetHandleVerifier [0x00007FF608274823+4057299]
        GetHandleVerifier [0x00007FF607F45C49+720121]
        (No symbol) [0x00007FF607E2126F]
        (No symbol) [0x00007FF607E1C304]
        (No symbol) [0x00007FF607E1C432]
        (No symbol) [0x00007FF607E0BD04]
        BaseThreadInitThunk [0x00007FFAEA78257D+29]
        RtlUserThreadStart [0x00007FFAEB8AAA58+40]

SUCCESS: The process with PID 11064 (child process of PID 13300) has been terminated.
SUCCESS: The process with PID 13868 (child process of PID 13300) has been terminated.
SUCCESS: The process with PID 28456 (child process of PID 13300) has been terminated.
SUCCESS: The process with PID 40372 (child process of PID 13300) has been terminated.
SUCCESS: The process with PID 40472 (child process of PID 13300) has been terminated.
SUCCESS: The process with PID 7940 (child process of PID 13300) has been terminated.
SUCCESS: The process with PID 13300 (child process of PID 6020) has been terminated.
SUCCESS: The process with PID 6020 (child process of PID 39592) has been terminated.

**Comment by obaskly** [comment]
issue is now fixed
