### ISSUE TITLE
The program is stuk in login page and reload again and again

### ISSUE THREAD

**Issue by Afrasiyab-khan** [obaskly/AiTextDetectionBypass#4]
Error:
Error during registration: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF634512142+3514994]
        (No symbol) [0x00007FF634130CE2]
        (No symbol) [0x00007FF633FD76AA]
        (No symbol) [0x00007FF634021860]
        (No symbol) [0x00007FF63402197C]
        (No symbol) [0x00007FF634064EE7]
        (No symbol) [0x00007FF63404602F]
        (No symbol) [0x00007FF6340628F6]
        (No symbol) [0x00007FF634045D93]
        (No symbol) [0x00007FF634014BDC]
        (No symbol) [0x00007FF634015C64]
        GetHandleVerifier [0x00007FF63453E16B+3695259]
        GetHandleVerifier [0x00007FF634596737+4057191]
        GetHandleVerifier [0x00007FF63458E4E3+4023827]
        GetHandleVerifier [0x00007FF6342604F9+689705]
        (No symbol) [0x00007FF63413C048]
        (No symbol) [0x00007FF634138044]
        (No symbol) [0x00007FF6341381C9]
        (No symbol) [0x00007FF6341288C4]
        BaseThreadInitThunk [0x00007FFA669A257D+29]
        RtlUserThreadStart [0x00007FFA67C0AA58+40]

**Comment by obaskly** [comment]
The problem has been fixed
