### ISSUE TITLE
The program puts the email and password into the password section only or doesn't put email at all just password

### ISSUE THREAD

**Issue by RandomNewUser2022** [obaskly/AiTextDetectionBypass#5]
![image](https://github.com/obaskly/AiTextDetectionBypass/assets/150843245/834ee009-df0b-41c1-8f5b-651c477439d4)

**Comment by obaskly** [comment]
I was trying a work around using pyautogui since the xpaths change everytime. But it seems it's causing issues.
I updated the code. Try it again please

**Comment by RandomNewUser2022** [comment]
I tried deleting and re-downloading the file and now it just doesnt put in any credentials at all it just keeps opening new tabs of the login page

**Comment by RandomNewUser2022** [comment]
Works perfectly now, thank you for fixing and creating this tool!

**Comment by obaskly** [comment]
u r wlcm
enjoy
