### ISSUE TITLE
The tool now does not check the "I agree to terms and conditions" check mark and is stuck at the registration page

### ISSUE THREAD

**Issue by The0d1n** [obaskly/AiTextDetectionBypass#6]
It opens the registration page and gets stuck after entering the email and password in their respective field. It's now unable to check the Terms and Conditions check mark.

**Comment by obaskly** [comment]
I updated the code.
Keep in mind that the xpaths keep changing, that's why the script is not able to locate the input/button everytime. When you encounter that issue, just copy paste the new xpath in lines 70, 73 for the email, and lines 93, 96 for the terms button.
