### ISSUE TITLE
Program stuck on login page

### ISSUE THREAD

**Issue by aquzx** [obaskly/AiTextDetectionBypass#7]
PS C:\Users\user\Documents\Github\AiTextDetectionBypass> python gui.py
Both XPaths failed to locate the email input.
Both XPaths failed to locate the terms button.
Error during registration: Timed out waiting for message
Error during registration: 'NoneType' object has no attribute 'is_displayed'
Error during registration: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.105)
Stacktrace:
        GetHandleVerifier [0x00007FF7914770C2+63090]
        (No symbol) [0x00007FF7913E2D12]
        (No symbol) [0x00007FF79127EC65]
        (No symbol) [0x00007FF79125CA7C]
        (No symbol) [0x00007FF7912ED687]
        (No symbol) [0x00007FF791302AC1]
        (No symbol) [0x00007FF7912E6D83]
        (No symbol) [0x00007FF7912B83A8]
        (No symbol) [0x00007FF7912B9441]
        GetHandleVerifier [0x00007FF79187262D+4238301]
        GetHandleVerifier [0x00007FF7918AF78D+4488509]
        GetHandleVerifier [0x00007FF7918A7A6F+4456479]
        GetHandleVerifier [0x00007FF791550606+953270]
        (No symbol) [0x00007FF7913EE5DF]
        (No symbol) [0x00007FF7913E92B4]
        (No symbol) [0x00007FF7913E93EB]
        (No symbol) [0x00007FF7913D9C24]
        BaseThreadInitThunk [0x00007FFA1576257D+29]
        RtlUserThreadStart [0x00007FFA16F4AA58+40]

Both XPaths failed to locate the email input.
Both XPaths failed to locate the terms button.
PS C:\Users\user\Documents\Github\AiTextDetectionBypass> 
<img width="959" alt="Screenshot 2024-04-04 172117" src="https://github.com/obaskly/AiTextDetectionBypass/assets/165921967/917a74ee-f15c-41c3-9290-6f599caa41f3">
<img width="959" alt="Screenshot 2024-04-04 171954" src="https://github.com/obaskly/AiTextDetectionBypass/assets/165921967/e69f6540-2bee-4bfd-a20a-6e25e86f0b48">

**Comment by MauerHaus** [comment]
The fix is not quite simple, but the updated XPath can be added in **Line 70** to this:

```python
WebDriverWait(driver, 2).until(
    EC.element_to_be_clickable((By.XPATH, "//input[contains(@class, 'cmaUraA')]"))
).send_keys(str(email))
```
And in **Line 93** to this:
```python
Copy code
driver.find_element(
    By.XPATH, "//div[@class='clickable-element bubble-element Group cmaUraC bubble-r-container flex row']/button"
).click()
```
Additionally, the tempmail package, specifically the API from this service, is broken, so a more comprehensive fix is needed.

**Comment by tonphamanh** [comment]
![Untitled](https://github.com/user-attachments/assets/95ab8f84-31bc-4c43-8086-c5f70605d09d)
I can not login via the temp email, please fix it!

**Comment by obaskly** [comment]
I am working on a solution. Please be patient

**Comment by Al-Battashi** [comment]
has a fix been made yet, its been 2 weeks.

**Comment by obaskly** [comment]
there is an update released.
please check now
