### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by Lucky-069** [obaskly/AiTextDetectionBypass#8]
, line 2, in <module>
    from PyQt6.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QLabel, QLineEdit, QComboBox, QFileDialog, QMessageBox
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.

**Comment by SergioPalGam** [comment]
Same error when trying to run the command python gui.py

**Comment by obaskly** [comment]
I don't get this error even when I tried different versions of python. Try running this command then run the script again: 

pip install --force-reinstall pyqt6

**Comment by Lucky-069** [comment]
I was able to run the script by using executables however the script is not able to go past login screen. It does enters login password but not email! I even tried to manually enter the email but it won't verify email and is stuck there!

**Comment by samarthd3sai** [comment]
PS C:\Users\samar\OneDrive\Desktop\AiTextDetectionBypass> python gui.py
Traceback (most recent call last):
  File "C:\Users\samar\OneDrive\Desktop\AiTextDetectionBypass\gui.py", line 5, in <module>
    from paraphraser import main
  File "C:\Users\samar\OneDrive\Desktop\AiTextDetectionBypass\paraphraser.py", line 3, in <module>
    from tempmail import EMail
ModuleNotFoundError: No module named 'tempmail'

i'm getting this error after doing pip install tempmail

**Comment by obaskly** [comment]
@samarthd3sai 
run `pip install -r requirements.txt` or `pip install tempmail-python`
