### ISSUE TITLE
Magic Link Expired

### ISSUE THREAD

**Issue by kevenwai** [obaskly/AiTextDetectionBypass#9]
Keep getting "magic link expired" on login page. Verification in the email inbox doesn't work.  Please advise.

**Comment by mohammedhank91** [comment]
> Keep getting "magic link expired" on login page. Verification in the email inbox doesn't work. Please advise.

Yes, there's an error in that. We will work on it and try to resolve it as soon as possible.

**Comment by obaskly** [comment]
Problem has been solved. Please check again
